name: wazo-asterisk-tcmalloc
namespace: wazocommunication
version: 1.0.0
author: Wazo authors
display_name: Asterisk TCMalloc
min_wazo_version: 22.01
tags:
  - asterisk
  - memory
homepage: https://github.com/wazo-communication/wazo-asterisk-tcmalloc-plugin
debian_depends:
  - libtcmalloc-minimal4
